export const CREATE_ADMIN = "CREATE_ADMIN";
export const LOGIN_ADMIN = "LOGIN_ADMIN";
export const FINDALL_ADMIN = "FINDALL_ADMIN";

// reducer type
export const ADMIN_DETAILS_LOADING = "ADMIN_DETAILS_LOADING"
export const ADMIN_DETAILS_LOADED = "ADMIN_DETAILS_LOADED";
export const ADMIN_DETAILS_FAILED = "ADMIN_DETAILS_FAILED";
